# Generated by Django 3.1.7 on 2021-05-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
