# Generated by Django 3.1.7 on 2021-06-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_contact_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
