# Generated by Django 3.1.7 on 2021-05-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_contact_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user1',
        ),
    ]
