# Generated by Django 3.1.7 on 2021-06-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
